---
- name: create and disable syncthing user
  user: name={{ syncthing_user }}
        shell=/bin/bash
        home={{ syncthing_home }}
        createhome=yes
        shell=/sbin/nologin
        password=!!

- name: create a sync folder
  file: path={{ syncthing_home }}/sync
        recurse=yes state=directory
        owner={{ syncthing_user }}
        group={{ syncthing_user }}
        mode=700

- name: create a bin folder for the syncthing binary
  file:
    path={{ syncthing_home }}/bin
    state=directory
    owner={{ syncthing_user }}
    group={{ syncthing_user }}
    mode=700

- name: get syncthing version
  shell: "{{ syncthing_home }}/bin/syncthing --version"
  changed_when: false
  ignore_errors: true
  register: version_info

- name: set fact syncthing_installed_version
  set_fact:
    syncthing_installed_version={{ version_info.stdout | regex_replace('syncthing.(v\d+\.\d+\.\d+).*', '\1') }}

- name: get latest version info
  uri:
    url=https://api.github.com/repos/syncthing/syncthing/releases/latest
    method=GET
    return_content=yes
  register: syncthing_latest_version_info

- name: set fact syncthing_version
  set_fact:
    syncthing_version="{{ (syncthing_latest_version_info.content|from_json).tag_name }}"
  when: syncthing_version == "latest"

- name: download syncthing
  get_url:
    url="https://github.com/syncthing/syncthing/releases/download/{{ syncthing_version }}/syncthing-{{ ansible_system|lower }}-{{ arch[ansible_architecture] }}-{{ syncthing_version }}.tar.gz"
    dest=/tmp/syncthing_{{syncthing_version}}.tar.gz
  when: version_info|failed or syncthing_installed_version != syncthing_version

- name: extract and install syncthing
  unarchive:
    src=/tmp/syncthing_{{ syncthing_version }}.tar.gz
    dest=/tmp
    copy=no
  when: version_info|failed or syncthing_installed_version != syncthing_version


- name: copy syncthing executable to home dir
  copy:
    src = /tmp/syncthing-{{ ansible_system|lower }}-{{ arch[ansible_architecture] }}-{{ syncthing_version }}/syncthing
    dest={{ syncthing_home }}/bin/syncthing
    remote_src=True
    owner={{ syncthing_user }}
    group={{ syncthing_user }}
    mode=700
  when: version_info|failed or syncthing_installed_version != syncthing_version

- name: systemd | install service
  template:
    src=syncthing.service
    dest=/etc/systemd/system/syncthing.service
    mode=755
  register: systemd_conf

- name: systemd | activate service
  service:
    name=syncthing
    enabled=yes
    state=started

- name: systemd | reload service
  service:
    name=syncthing
    state=restarted
  when: systemd_conf|changed or version_info|failed or syncthing_installed_version != syncthing_version

- name: waiting for configfile (takes some time)
  wait_for: path={{ syncthing_home }}/.config/syncthing/config.xml

- name: syncthing | config.xml set webinterface address
  xml:
    file={{ syncthing_home }}/.config/syncthing/config.xml
    xpath=/configuration/gui/address
    value={{ syncthing_address }}
  notify: restart syncthing

- name: syncthing | config.xml set listen address
  xml:
    file={{ syncthing_home }}/.config/syncthing/config.xml
    xpath=/configuration/options/listenAddress
    value={{ syncthing_listen }}
  notify: restart syncthing

- name: syncthing | config.xml set localAnnounceEnabled
  xml:
    file={{ syncthing_home }}/.config/syncthing/config.xml
    xpath=/configuration/options/localAnnounceEnabled
    value={{ syncthing_localannounce|lower }}
  notify: restart syncthing

- name: syncthing | config.xml set globalAnnounceEnabled
  xml:
    file={{ syncthing_home }}/.config/syncthing/config.xml
    xpath=/configuration/options/globalAnnounceEnabled
    value={{ syncthing_globalannounce|lower }}
  notify: restart syncthing

- name: syncthing | config.xml set upnpEnabled
  xml:
    file={{ syncthing_home }}/.config/syncthing/config.xml
    xpath=/configuration/options/upnpEnabled
    value={{ syncthing_upnp|lower }}
  notify: restart syncthing

- name: syncthing | config.xml set user
  xml:
    file={{ syncthing_home }}/.config/syncthing/config.xml
    xpath=/configuration/gui/user
    value={{ syncthing_gui_user }}
  when: syncthing_gui_user is defined
  notify: restart syncthing

- name: syncthing | config.xml set password
  xml:
    file={{ syncthing_home }}/.config/syncthing/config.xml
    xpath=/configuration/gui/password
    value={{ syncthing_gui_password }}
  when: syncthing_gui_password is defined
  notify: restart syncthing

